## Stage 1 Build
FROM node:20 AS builder
LABEL author="test.main@gmail.com"
WORKDIR /app
COPY ./node_project/* /app
RUN npm install
RUN npm install -g typescript nodemon mocha


# Stage 2
FROM node:20-alpine AS runner
WORKDIR /app

# We copy essential files
COPY --from=builder /app/*.json /app
COPY --from=builder /app/node_modules /app
COPY --from=builder /app/app.js /app

EXPOSE 3500
ENTRYPOINT [ "node" ]
CMD [ "app.js" ]

