## Stage 1 Build
FROM node:20 AS builder
LABEL author="test.main@gmail.com"
WORKDIR /app
COPY ./node_project/* ./
RUN npm install
RUN npm install -g typescript nodemon mocha


# Stage 2
FROM node:20-alpine AS runner
WORKDIR /app

# We copy essential files
COPY --from=builder /app/*.json .
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/app.js .

EXPOSE 3500
ENTRYPOINT [ "node" ]
CMD [ "app.js" ]

