services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api_volume_image:1.0
    container_name: api_container-compose
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
      # - /mnt/c/Users/MaxwellAdomako/devops/docker-crash-course/api/node_modules:/app/node_modules
