version: "3.8"
services:
  api:
    build: ./api
    image: api_image:1.0
    container_name: api_container
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./api/node_modules
      - /mnt/c/Users/MaxwellAdomako/devops/docker-crash-course/api/node_modules:/app/node_modules
