global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "docker"
    static_configs:
      - targets: ["localhost:9323"]

  - job_name: "docker_containers"
    static_configs:
      - targets: ["localhost:8083"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["localhost:8585"]

  - job_name: "nginx"
    static_configs:
      - targets: ["localhost:8081"]

  # Optional: only if you fix this
  # - job_name: "remote_collector"
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ["192.168.1.100:9100"]  # or remove
