FROM node:20-alpine

LABEL author="test.main@gmail.com"

WORKDIR /usr/app

# Specifying paths relative to the WORKDIR and packaging only necessary files
COPY ./node_project/* /usr/app/
RUN npm install

COPY . .

EXPOSE 3000

CMD ["node", "app.js"]
