services: 
  app:
    image: multistage-node-app:1.2
    build:
      context: .
      dockerfile: docker/Dockerfile.multistage
      # container_name: single_stage_node_app
    container_name: multistage-cont
    ports:
      - "3500:3500"
    # volumes:
    # # Mounting the entire project directory to reflect changes in real-time
    #   - ./node_project:/app
    # # mounting node_modules to avoid overwriting by the host volume added above.
    #   - /app/node_modules

