# Service: 
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile.singlestage
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./section-4-demo-practice/node_project:/usr/app

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.singlestage
      # container_name: single_stage_node_app
    container_name: single_stage_node_app
    ports:
      - "3000:3000"
    volumes:
    # Mounting the entire project directory to reflect changes in real-time
      - ./node_project/:/usr/app
    # mounting node_modules to avoid overwriting by the host volume added above.
      - /usr/app/node_modules


