# Service: 
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile.singlestage
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./section-4-demo-practice/node_project:/usr/app

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.singlestage
      # container_name: single_stage_node_app
    container_name: single_stage_node_app
    ports:
      - "3000:3000"
    volumes:
      - ./node_project:/usr/app
    command: node app.js

